Added side bar and integrated api's with dummy application.
bigbinary/neeto_tags_frontend pull request #7
Opened 2022-05-06 07:30 UTC by mayanksharma4132

closes #6

2022-05-16 10:31 UTC, mayanksharma4132 commented
@karthiknmenon
Please check.

2022-05-18 16:45 UTC, mayanksharma4132 commented
@karthiknmenon please check.

2022-05-20 06:07 UTC, karthiknmenon requested changes
@mayanksharma4132 _a Please check.

2022-05-20 06:07 UTC, karthiknmenon commented on src/components/ManageTags.jsx
> +                    label="Tag Name"
We should be localising texts, but we can do it in a separate PR.

2022-05-20 06:07 UTC, karthiknmenon commented on src/components/index.jsx
> +  const [pane, setPane] = useState(null);
Please name states properly.

2022-05-20 06:07 UTC, karthiknmenon commented on src/components/index.jsx
> +      setTagsCount(data.total_count);
We would need to move the entire API logic to react-query. Let's take it up as a separate issue in the end.

2022-05-20 06:07 UTC, karthiknmenon commented on src/components/index.jsx
> +      const { data } = await tagsApi.fetch(
Since, we only require `tags` and `total_count`, I would prefer restructuring data here itself.

2022-05-20 06:07 UTC, karthiknmenon commented on src/components/index.jsx
> +            {"Are you sure you want to delete tag"}{" "}
Do we need braces here?

2022-05-20 06:07 UTC, karthiknmenon commented on src/components/index.jsx
> +            {"This action cannot be undone."}
also here.

2022-05-20 06:07 UTC, karthiknmenon commented on src/components/util.js
> +import { Dropdown, Button } from "@bigbinary/neetoui";
Please create aliases for neetoUI and neetoIcons.

2022-05-20 06:07 UTC, karthiknmenon commented on src/components/ManageTags.jsx
> +      fetchTags();
I prefer doing optimistic updates here. Can't we send the updated tag in the response and add it to the already existing state? 
This would prevent an unwanted fetch API call.

2022-05-20 06:13 UTC, mayanksharma4132 commented on src/components/ManageTags.jsx
> +                    label="Tag Name"
created https://github.com/bigbinary/neeto_tags_frontend/issues/10.

2022-05-20 06:16 UTC, mayanksharma4132 commented on src/components/index.jsx
> +      setTagsCount(data.total_count);
create https://github.com/bigbinary/neeto_tags_frontend/issues/11.

2022-05-20 06:38 UTC, mayanksharma4132 commented
@karthiknmenon _a
Please check.

2022-05-30 13:44 UTC, chiraggshah commented
@karthiknmenon : Can we get this reviewed and merged?

2022-05-30 14:22 UTC, karthiknmenon commented
@chiraggshah Had missed the notification. Changes LGTM.

2022-05-30 14:23 UTC, merged